name: test-code-check

on:
  pull_request:

env:
  DIR: .github/workflows/scripts

jobs:
  check-internal-keyword:
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install endpoint dependencies
      run: |
        cd ${{ env.DIR }}/endpoint-check
        npm install
 
    - id: changed
      name: Check changed files
      run: |
        BASE_SHA="${{ github.event.pull_request.base.sha }}"
        HEAD_SHA="${{ github.event.pull_request.head.sha }}"
        FILES=$(git diff --name-only --diff-filter=AM HEAD~$(git rev-list --count HEAD) -- '*.ts' '*.js')
        if [ -z "$FILES" ]; then
          echo "No changed files detected."
        else
          echo "Changed files: $FILES"
          # Replace newlines with commas for GitHub Actions compatibility
          FILES=$(echo "$FILES" | tr '\n' ',')
          echo "files=$FILES" >> $GITHUB_OUTPUT
        fi


    - name: Run internal keyword check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        FILES: ${{ steps.changed.outputs.files }} 
      run: |
        node ${{ env.DIR }}/endpoint-check/endpoint-check.js
